// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/delivery/grpc/room_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsRequest) Reset() {
	*x = GetRoomsRequest{}
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsRequest) ProtoMessage() {}

func (x *GetRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomsRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_room_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomsRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type GetRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsResponse) Reset() {
	*x = GetRoomsResponse{}
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsResponse) ProtoMessage() {}

func (x *GetRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_room_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        int64                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	IsBooked      bool                   `protobuf:"varint,3,opt,name=is_booked,json=isBooked,proto3" json:"is_booked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_room_service_proto_rawDescGZIP(), []int{2}
}

func (x *Room) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Room) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Room) GetIsBooked() bool {
	if x != nil {
		return x.IsBooked
	}
	return false
}

type BookRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRoomRequest) Reset() {
	*x = BookRoomRequest{}
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRoomRequest) ProtoMessage() {}

func (x *BookRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRoomRequest.ProtoReflect.Descriptor instead.
func (*BookRoomRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_room_service_proto_rawDescGZIP(), []int{3}
}

func (x *BookRoomRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type BookRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRoomResponse) Reset() {
	*x = BookRoomResponse{}
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRoomResponse) ProtoMessage() {}

func (x *BookRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRoomResponse.ProtoReflect.Descriptor instead.
func (*BookRoomResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_room_service_proto_rawDescGZIP(), []int{4}
}

type ReleaseRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRoomRequest) Reset() {
	*x = ReleaseRoomRequest{}
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRoomRequest) ProtoMessage() {}

func (x *ReleaseRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRoomRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRoomRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_room_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseRoomRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type ReleaseRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRoomResponse) Reset() {
	*x = ReleaseRoomResponse{}
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRoomResponse) ProtoMessage() {}

func (x *ReleaseRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_room_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRoomResponse.ProtoReflect.Descriptor instead.
func (*ReleaseRoomResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_room_service_proto_rawDescGZIP(), []int{6}
}

var File_internal_delivery_grpc_room_service_proto protoreflect.FileDescriptor

const file_internal_delivery_grpc_room_service_proto_rawDesc = "" +
	"\n" +
	")internal/delivery/grpc/room_service.proto\x12\vroomservice\"/\n" +
	"\x0fGetRoomsRequest\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\";\n" +
	"\x10GetRoomsResponse\x12'\n" +
	"\x05rooms\x18\x01 \x03(\v2\x11.roomservice.RoomR\x05rooms\"K\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x03R\x06number\x12\x1b\n" +
	"\tis_booked\x18\x03 \x01(\bR\bisBooked\")\n" +
	"\x0fBookRoomRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\"\x12\n" +
	"\x10BookRoomResponse\",\n" +
	"\x12ReleaseRoomRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\"\x15\n" +
	"\x13ReleaseRoomResponse2\xf1\x01\n" +
	"\vRoomService\x12G\n" +
	"\bGetRooms\x12\x1c.roomservice.GetRoomsRequest\x1a\x1d.roomservice.GetRoomsResponse\x12G\n" +
	"\bBookRoom\x12\x1c.roomservice.BookRoomRequest\x1a\x1d.roomservice.BookRoomResponse\x12P\n" +
	"\vReleaseRoom\x12\x1f.roomservice.ReleaseRoomRequest\x1a .roomservice.ReleaseRoomResponseB\rZ\vinternal/pbb\x06proto3"

var (
	file_internal_delivery_grpc_room_service_proto_rawDescOnce sync.Once
	file_internal_delivery_grpc_room_service_proto_rawDescData []byte
)

func file_internal_delivery_grpc_room_service_proto_rawDescGZIP() []byte {
	file_internal_delivery_grpc_room_service_proto_rawDescOnce.Do(func() {
		file_internal_delivery_grpc_room_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_delivery_grpc_room_service_proto_rawDesc), len(file_internal_delivery_grpc_room_service_proto_rawDesc)))
	})
	return file_internal_delivery_grpc_room_service_proto_rawDescData
}

var file_internal_delivery_grpc_room_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_delivery_grpc_room_service_proto_goTypes = []any{
	(*GetRoomsRequest)(nil),     // 0: roomservice.GetRoomsRequest
	(*GetRoomsResponse)(nil),    // 1: roomservice.GetRoomsResponse
	(*Room)(nil),                // 2: roomservice.Room
	(*BookRoomRequest)(nil),     // 3: roomservice.BookRoomRequest
	(*BookRoomResponse)(nil),    // 4: roomservice.BookRoomResponse
	(*ReleaseRoomRequest)(nil),  // 5: roomservice.ReleaseRoomRequest
	(*ReleaseRoomResponse)(nil), // 6: roomservice.ReleaseRoomResponse
}
var file_internal_delivery_grpc_room_service_proto_depIdxs = []int32{
	2, // 0: roomservice.GetRoomsResponse.rooms:type_name -> roomservice.Room
	0, // 1: roomservice.RoomService.GetRooms:input_type -> roomservice.GetRoomsRequest
	3, // 2: roomservice.RoomService.BookRoom:input_type -> roomservice.BookRoomRequest
	5, // 3: roomservice.RoomService.ReleaseRoom:input_type -> roomservice.ReleaseRoomRequest
	1, // 4: roomservice.RoomService.GetRooms:output_type -> roomservice.GetRoomsResponse
	4, // 5: roomservice.RoomService.BookRoom:output_type -> roomservice.BookRoomResponse
	6, // 6: roomservice.RoomService.ReleaseRoom:output_type -> roomservice.ReleaseRoomResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_delivery_grpc_room_service_proto_init() }
func file_internal_delivery_grpc_room_service_proto_init() {
	if File_internal_delivery_grpc_room_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_delivery_grpc_room_service_proto_rawDesc), len(file_internal_delivery_grpc_room_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_delivery_grpc_room_service_proto_goTypes,
		DependencyIndexes: file_internal_delivery_grpc_room_service_proto_depIdxs,
		MessageInfos:      file_internal_delivery_grpc_room_service_proto_msgTypes,
	}.Build()
	File_internal_delivery_grpc_room_service_proto = out.File
	file_internal_delivery_grpc_room_service_proto_goTypes = nil
	file_internal_delivery_grpc_room_service_proto_depIdxs = nil
}
